import { useNavigate } from 'react-router-dom';

const Home = () => {
  const navigate = useNavigate();

  return (
    <div className="bg-bg-base text-text-primary min-h-screen w-full flex flex-col justify-between p-gutter relative font-body overflow-x-hidden">
      {/* Background Grid Pattern */}
      <div className="absolute inset-0 pointer-events-none" style={{ backgroundImage: 'linear-gradient(to right, #30363D 1px, transparent 1px), linear-gradient(to bottom, #30363D 1px, transparent 1px)', backgroundSize: '40px 40px', opacity: 0.1 }}></div>
      
      {/* Top Header */}
      <header className="max-w-6xl w-full mx-auto flex justify-between items-center h-16 relative z-10 shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded bg-primary-container flex items-center justify-center">
            <span className="material-symbols-outlined text-on-primary-container" style={{ fontVariationSettings: "'FILL' 1" }}>neurology</span>
          </div>
          <span className="font-headline-md text-xl font-extrabold text-primary tracking-tight">PrepIntAI</span>
        </div>
        <button
          onClick={() => navigate('/setup')}
          className="bg-surface-variant hover:bg-outline-variant text-text-primary font-semibold text-xs py-2 px-4 rounded transition-all active:scale-95 duration-100"
        >
          Sign In
        </button>
      </header>

      {/* Main Hero Body */}
      <main className="max-w-6xl w-full mx-auto flex-1 flex flex-col lg:flex-row items-center justify-center gap-12 py-12 relative z-10">
        {/* Left Text Panel */}
        <div className="flex-1 space-y-6 text-left max-w-xl">
          <div className="inline-flex items-center gap-2 bg-primary/10 border border-primary/20 text-primary py-1 px-3 rounded-full text-xs font-semibold">
            <span className="w-1.5 h-1.5 bg-primary rounded-full animate-pulse"></span>
            AI Mock Interview Coach
          </div>
          <h1 className="font-display text-5xl font-extrabold text-on-surface leading-tight tracking-tight">
            Crack Technical Interviews with <span className="text-primary">PrepIntAI</span>
          </h1>
          <p className="font-body text-text-secondary text-base leading-relaxed">
            Configure custom mock assessments on Java, React, DSA, or system design. Write or dictate your answers, and receive detailed scores, strengths, weaknesses, and perfect model solutions generated by Gemini.
          </p>
          <div className="flex items-center gap-4 pt-2">
            <button
              onClick={() => navigate('/setup')}
              className="bg-primary hover:bg-primary/95 text-white font-bold text-sm py-3 px-8 rounded flex items-center gap-2 shadow-lg hover:shadow-primary/10 transition-all active:scale-95 duration-100"
            >
              Start Practicing
              <span className="material-symbols-outlined text-sm" style={{ fontVariationSettings: "'FILL' 1" }}>play_arrow</span>
            </button>
            <button
              onClick={() => window.open('https://github.com', '_blank')}
              className="border border-border-muted hover:bg-surface-variant text-text-primary font-semibold text-sm py-3 px-8 rounded transition-all active:scale-95 duration-100"
            >
              View on GitHub
            </button>
          </div>
        </div>

        {/* Right Preview Panel (GitHub-Style Bento Dashboard Mockup) */}
        <div className="flex-1 w-full max-w-lg bg-bg-card border border-border-muted rounded-xl p-6 shadow-2xl relative">
          <div className="flex justify-between items-center mb-6 pb-3 border-b border-border-muted">
            <span className="text-xs text-text-secondary font-bold uppercase tracking-wider">Practice Dashboard Preview</span>
            <div className="flex gap-1.5">
              <span className="w-3 h-3 rounded-full bg-danger/40"></span>
              <span className="w-3 h-3 rounded-full bg-warning/40"></span>
              <span className="w-3 h-3 rounded-full bg-success/40"></span>
            </div>
          </div>
          <div className="space-y-4">
            <div className="bg-bg-base border border-border-muted p-4 rounded-lg flex justify-between items-center">
              <div>
                <p className="text-[10px] text-text-secondary font-bold uppercase tracking-wider">Latest Score</p>
                <h4 className="text-lg font-bold text-success">92 / 100</h4>
              </div>
              <span className="bg-success/10 text-success border border-success/20 py-1 px-2.5 rounded text-[10px] font-bold">Exceptional</span>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="bg-bg-base border border-border-muted p-3 rounded-lg text-center">
                <p className="text-[9px] text-text-secondary font-bold uppercase tracking-wider mb-1">Time Spent</p>
                <p className="text-sm font-bold text-text-primary">125 mins</p>
              </div>
              <div className="bg-bg-base border border-border-muted p-3 rounded-lg text-center">
                <p className="text-[9px] text-text-secondary font-bold uppercase tracking-wider mb-1">Status</p>
                <p className="text-sm font-bold text-primary">5 Sessions</p>
              </div>
            </div>

            <div className="bg-bg-base border border-border-muted p-4 rounded-lg space-y-2">
              <p className="text-[10px] text-text-secondary font-bold uppercase tracking-wider">Topic Consistency</p>
              <div className="flex gap-1">
                {[80, 95, 40, 100, 20, 85, 90, 75, 60, 95, 100, 30].map((h, i) => (
                  <div
                    key={i}
                    className="flex-1 bg-border-muted rounded-sm transition-colors hover:bg-primary"
                    style={{
                      height: '24px',
                      backgroundColor: h >= 80 ? '#238636' : h >= 50 ? '#D29922' : '#30363D'
                    }}
                  ></div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="max-w-6xl w-full mx-auto py-6 border-t border-border-muted text-center text-xs text-text-secondary relative z-10 shrink-0">
        PrepIntAI © {new Date().getFullYear()} — Built for developers. Powered by Gemini API.
      </footer>
    </div>
  );
};

export default Home;