// ─────────────────────────────────────────────────────────────────────────────
// pages/Home.jsx — LANDING / OVERVIEW PAGE
//
// This is a PUBLIC PAGE — accessible at the root URL (/)
//
// What it does:
//   • Fetches the user's interview history via getHistory() from services/api.js
//   • Displays a hero section, feature highlights, and a recent history preview
//   • Provides navigation buttons to login/signup or start an interview
//
// Note: getHistory() requires auth, but this page doesn't redirect if the
// call fails — it just shows an empty state. Real auth protection is on
// /dashboard and its sub-routes via ProtectedRoute.
// ─────────────────────────────────────────────────────────────────────────────
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getHistory, wakeupBackend } from '../services/api';

const HomePage = () => {
  const navigate = useNavigate();
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Fire a lightweight, unauthenticated request to wake up the Render backend
    wakeupBackend();

    getHistory()
      .then((data) => {
        setHistory(data);
        setLoading(false);
      })
      .catch((err) => {
        console.error("Failed to load history:", err);
        setLoading(false);
      });
  }, []);

  const totalSessions = history.length;
  const averageScore = totalSessions > 0 
    ? Math.round(history.reduce((sum, item) => sum + item.overallScore, 0) / totalSessions)
    : 0;

  return (
    <div className="text-text-primary min-h-screen w-full flex flex-col justify-between p-4 md:p-6 relative font-body overflow-x-hidden bg-transparent">
      
      {/* Top Header */}
      <header className="max-w-6xl w-full mx-auto flex justify-between items-center h-16 relative z-10 shrink-0">
        <div className="flex items-center gap-1.5">
          <h1 className="font-headline-lg text-headline-md font-bold text-primary flex items-center justify-center gap-2">
            <span className="material-symbols-outlined text-white" style={{ fontVariationSettings: "'FILL' 1" }}>terminal</span>
            PREPINTAI
          </h1>
        </div>
      </header>

      {/* Main Hero Body */}
      <main className="max-w-6xl w-full mx-auto flex-1 flex flex-col lg:flex-row items-center justify-center gap-12 py-12 relative z-10 w-full">
        {/* Left Text Panel */}
        <div className="space-y-6 flex-1 max-w-xl text-left">
          <div className="inline-flex items-center gap-2 bg-primary/10 border border-primary/20 text-primary py-1 px-3 rounded-full text-xs font-semibold">
            <span className="w-1.5 h-1.5 bg-primary rounded-full animate-pulse"></span>
            AI Mock Interview Coach
          </div>
          <h1 className="font-display text-3xl sm:text-4xl font-extrabold text-on-surface leading-tight tracking-tight">
            Crack Technical Interviews with <span className="text-primary">PREPINTAI</span>
          </h1>
          <p className="font-body text-text-secondary text-base leading-relaxed">
            Configure custom mock assessments on Java, React, DSA, or system design. Write or dictate your answers, and receive detailed scores, strengths, weaknesses, and perfect model solutions generated by Gemini.
          </p>
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4 pt-2 w-full">
            <button
              onClick={() => navigate('/dashboard')}
              className="bg-primary text-on-primary font-bold py-2.5 px-5 h-11 w-full sm:w-48 rounded-md shadow-md hover:opacity-90 active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 cursor-pointer"
            >
              Start Practicing
              <span className="material-symbols-outlined text-sm leading-none" style={{ fontVariationSettings: "'FILL' 1" }}>play_arrow</span>
            </button>
            <button
              onClick={() => window.open('https://github.com', '_blank')}
              className="bg-surface-variant text-text-primary border border-border-muted font-semibold py-2.5 px-5 h-11 w-full sm:w-48 rounded-md hover:bg-outline-variant active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 cursor-pointer"
            >
              View on GitHub
            </button>
          </div>
        </div>

        {/* Right Panel: Dynamic Practice Dashboard / History Log */}
        <div className="flex-1 w-full max-w-lg bg-bg-card border border-border-muted rounded-xl p-5 md:p-6 shadow-2xl relative overflow-hidden flex flex-col h-[400px]">
          <div className="flex justify-between items-center mb-4 pb-3 border-b border-border-muted shrink-0">
            <span className="text-xs text-text-secondary font-bold uppercase tracking-wider">
              {history.length > 0 ? "Your Practice History" : "Practice Dashboard Preview"}
            </span>
            <div className="flex gap-1.5">
              <span className="w-3 h-3 rounded-full bg-danger/40"></span>
              <span className="w-3 h-3 rounded-full bg-warning/40"></span>
              <span className="w-3 h-3 rounded-full bg-success/40"></span>
            </div>
          </div>

          {loading ? (
            <div className="flex-1 flex flex-col items-center justify-center">
              <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"></div>
            </div>
          ) : history.length > 0 ? (
            <div className="flex-1 flex flex-col min-h-0">
              {/* Dynamic Stats Header */}
              <div className="grid grid-cols-2 gap-3 mb-4 shrink-0">
                <div className="bg-bg-base border border-border-muted p-3 rounded-lg text-center">
                  <p className="text-[9px] text-text-secondary font-bold uppercase tracking-wider mb-1">Total Sessions</p>
                  <p className="text-sm font-bold text-text-primary">{totalSessions}</p>
                </div>
                <div className="bg-bg-base border border-border-muted p-3 rounded-lg text-center">
                  <p className="text-[9px] text-text-secondary font-bold uppercase tracking-wider mb-1">Average Score</p>
                  <p className={`text-sm font-bold ${averageScore >= 80 ? 'text-success' : averageScore >= 50 ? 'text-warning' : 'text-danger'}`}>
                    {averageScore}%
                  </p>
                </div>
              </div>

              {/* Scrollable History List */}
              <p className="text-[10px] text-text-secondary font-bold uppercase tracking-wider mb-2 shrink-0">Completed Assessments</p>
              <div className="flex-1 overflow-y-auto space-y-2 pr-1">
                {history.map((session) => {
                  const date = new Date(session.createdAt);
                  const formattedDate = date.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
                  
                  return (
                    <div key={session.id} className="bg-bg-base border border-border-muted p-3 rounded-lg flex items-center justify-between hover:border-outline-variant transition-colors gap-3">
                      <div className="min-w-0 flex-1 text-left">
                        <h4 className="text-xs font-bold text-on-surface truncate">{session.topic}</h4>
                        <p className="text-[10px] text-text-secondary font-semibold mt-0.5">{session.experienceLevel} • {formattedDate}</p>
                      </div>
                      <div className="flex items-center gap-3 shrink-0">
                        <span className={`text-xs font-code font-bold border px-2 py-0.5 rounded-full ${
                          session.overallScore >= 80 ? 'text-success border-success/20 bg-success/5' :
                          session.overallScore >= 50 ? 'text-warning border-warning/20 bg-warning/5' :
                          'text-danger border-danger/20 bg-danger/5'
                        }`}>
                          {session.overallScore}%
                        </span>
                        <button
                          onClick={() => navigate(`/report/${session.id}`)}
                          className="bg-surface-variant hover:bg-outline-variant text-[10px] font-bold py-1 px-2.5 rounded transition-all active:scale-95 duration-100 flex items-center gap-0.5 cursor-pointer"
                        >
                          Details
                          <span className="material-symbols-outlined text-[10px]">chevron_right</span>
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          ) : (
            /* Static Demo Layout when History is Empty */
            <div className="flex-1 flex flex-col justify-between">
              <div className="space-y-4">
                <div className="bg-bg-base border border-border-muted p-4 rounded-lg flex justify-between items-center">
                  <div>
                    <p className="text-[10px] text-text-secondary font-bold uppercase tracking-wider">Latest Score</p>
                    <h4 className="text-lg font-bold text-success">92 / 100</h4>
                  </div>
                  <span className="bg-success/10 text-success border border-success/20 py-1 px-2.5 rounded text-[10px] font-bold">Exceptional</span>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div className="bg-bg-base border border-border-muted p-3 rounded-lg text-center">
                    <p className="text-[9px] text-text-secondary font-bold uppercase tracking-wider mb-1">Time Spent</p>
                    <p className="text-sm font-bold text-text-primary">125 mins</p>
                  </div>
                  <div className="bg-bg-base border border-border-muted p-3 rounded-lg text-center">
                    <p className="text-[9px] text-text-secondary font-bold uppercase tracking-wider mb-1">Status</p>
                    <p className="text-sm font-bold text-primary">5 Sessions</p>
                  </div>
                </div>

                <div className="bg-bg-base border border-border-muted p-4 rounded-lg space-y-2">
                  <p className="text-[10px] text-text-secondary font-bold uppercase tracking-wider">Topic Consistency</p>
                  <div className="flex gap-1">
                    {[80, 95, 40, 100, 20, 85, 90, 75, 60, 95, 100, 30].map((h, i) => (
                      <div
                        key={i}
                        className="flex-1 bg-border-muted rounded-sm transition-colors hover:bg-primary"
                        style={{
                          height: '24px',
                          backgroundColor: h >= 80 ? '#238636' : h >= 50 ? '#D29922' : '#30363D'
                        }}
                      ></div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default HomePage;